In [21]:
import pandas as pd

df_category = pd.read_csv("../data/sales_by_category_state.csv")
df_category.head()

,customer_state,product_category,category_order_count,order_item_line_count,category_gmv,category_gmv_per_order
0,AC,sports_leisure,9,9,1677.46,186.384444
1,AC,watches_gifts,4,4,1389.60,347.400000
2,AC,health_beauty,6,7,1386.58,231.096667
3,AC,furniture_decor,7,12,1316.44,188.062857
4,AC,computers_accessories,6,8,1238.50,206.416667

In [2]:
df_category.shape

(1388, 6)

In [3]:
df_category.dtypes

customer_state                str
product_category              str
category_order_count        int64
order_item_line_count       int64
category_gmv              float64
category_gmv_per_order    float64
dtype: object

In [4]:
df_category.isnull().sum()

customer_state            0
product_category          0
category_order_count      0
order_item_line_count     0
category_gmv              0
category_gmv_per_order    0
dtype: int64

In [5]:
df_category.duplicated().sum()

np.int64(0)

In [6]:
df_category.describe().T

,count,mean,std,min,25%,50%,75%,max
category_order_count,1388.0,70.083573,268.113458,1.0,2.00,8.000000,33.000000,4347.00
order_item_line_count,1388.0,79.392651,308.366898,1.0,3.00,8.000000,37.000000,5157.00
category_gmv,1388.0,9525.575007,33185.958310,6.8,311.15,1309.380000,5764.947500,472238.07
category_gmv_per_order,1388.0,195.974273,246.016877,6.8,90.00,132.529687,200.784233,2919.40

In [ ]:
df_category.groupby("customer_state")[[
    "category_order_count", 
    "order_item_line_count", 
    "category_gmv", 
    "category_gmv_per_order"
    ]].describe()

               category_order_count                                            \
                              count        mean         std  min   25%    50%
customer_state
AC                             28.0    2.892857    2.096545  1.0   1.0    2.0
AL                             43.0    9.232558   12.424701  1.0   1.0    4.0
AM                             38.0    3.815789    3.797974  1.0   1.0    2.0
AP                             21.0    3.190476    2.315579  1.0   2.0    2.0
BA                             63.0   52.079365   76.126868  1.0   5.0   11.0
CE                             53.0   24.283019   33.865331  1.0   2.0    7.0
DF                             61.0   34.295082   51.515805  1.0   4.0    7.0
ES                             59.0   34.016949   48.537398  1.0   3.0   10.0
GO                             63.0   31.428571   48.101946  1.0   3.0    6.0
MA                             47.0   15.340426   19.988341  1.0   1.0    5.0
MG                             71.0  161.366197  263.265387  1.0  10.0   28.0
MS                             55.0   12.800000   16.408444  1.0   1.5    4.0
MT                             54.0   16.555556   21.269756  1.0   2.0    5.5
PA                             52.0   18.288462   24.464730  1.0   1.0    4.5
PB                             47.0   11.021277   14.379166  1.0   1.0    4.0
PE                             57.0   28.052632   43.685737  1.0   3.0    6.0
PI                             48.0    9.979167   11.997322  1.0   2.0    4.0
PR                             65.0   76.353846  114.433309  1.0   7.0   14.0
RJ                             71.0  175.633803  286.359626  1.0  10.5   40.0
RN                             46.0   10.369565   12.438933  1.0   1.0    4.5
RO                             42.0    5.833333    5.716543  1.0   1.0    4.5
RR                             17.0    2.411765    1.543487  1.0   1.0    2.0
RS                             68.0   79.514706  126.953922  1.0   5.0   17.0
SC                             65.0   54.969231   82.567769  1.0   4.0   13.0
SE                             42.0    8.000000    9.730515  1.0   1.0    3.0
SP                             73.0  559.301370  943.379235  2.0  32.0  109.0
TO                             39.0    7.051282    7.772924  1.0   1.0    3.0

                               order_item_line_count              ...  \
                   75%     max                 count        mean  ...
customer_state                                                    ...
AC                4.00     9.0                  28.0    3.250000  ...
AL               12.00    62.0                  43.0    9.930233  ...
AM                4.75    15.0                  38.0    4.289474  ...
AP                4.00    10.0                  21.0    3.857143  ...
BA               71.50   319.0                  63.0   58.460317  ...
CE               40.00   152.0                  53.0   26.905660  ...
DF               43.00   219.0                  61.0   38.606557  ...
ES               53.50   197.0                  59.0   37.711864  ...
GO               43.00   206.0                  63.0   36.142857  ...
MA               21.50    82.0                  47.0   17.021277  ...
MG              198.50  1120.0                  71.0  181.915493  ...
MS               20.00    60.0                  55.0   14.745455  ...
MT               23.50    83.0                  54.0   19.203704  ...
PA               27.50    99.0                  52.0   20.269231  ...
PB               15.50    75.0                  47.0   12.468085  ...
PE               41.00   220.0                  57.0   30.631579  ...
PI               14.25    50.0                  48.0   10.895833  ...
PR              107.00   420.0                  65.0   86.907692  ...
RJ              191.00  1357.0                  71.0  199.197183  ...
RN               19.25    56.0                  46.0   11.326087  ...
RO                9.50    23.0                  42.0    6.500000  ...
RR                3.00     6.0                  17.0    2.705882  ...
RS               79.75   537.0                  68.0   90.205882  ...
SC               79.00   309.0                  65.0   63.030769  ...
SE               11.75    38.0                  42.0    8.928571  ...
SP              562.00  4347.0                  73.0  636.273973  ...
TO               11.50    29.0                  39.0    7.948718  ...

               category_gmv            category_gmv_per_order              \
                        75%        max                  count        mean
customer_state
AC                 799.3700    1677.46                   28.0  201.099588
AL                2122.9450   12681.26                   43.0  270.954365
AM                 716.1675    2776.03                   38.0  195.339897
AP                 812.6900    2050.03                   21.0  238.934729
BA                9676.7050   49955.12                   63.0  177.525487
CE                5980.8400   31544.50                   53.0  200.484891
DF                6049.5400   32292.27                   61.0  182.925070
ES                7317.7750   28074.00                   59.0  194.730053
GO                4623.2350   31486.93                   63.0  185.812092
MA                3840.1350   12668.28                   47.0  202.526931
MG               23779.4050  154324.15                   71.0  167.984276
MS                2377.9050   11231.58                   55.0  177.812727
MT                3606.1000   15241.80                   54.0  276.114746
PA                4034.0075   23545.84                   52.0  213.703197
PB                3234.7450   15692.08                   47.0  286.743013
PE                5611.9200   40685.01                   57.0  193.887275
PI                2389.0150   10205.20                   48.0  181.563114
PR               10458.2900   57653.30                   65.0  167.001970
RJ               27173.8600  174895.01                   71.0  164.810861
RN                2504.5575   13728.98                   46.0  171.799290
RO                1506.1750    7085.76                   42.0  214.031174
RR                 518.1000    1350.60                   17.0  207.454676
RS               10824.5625   60040.95                   68.0  170.837437
SC                8658.0100   41579.03                   65.0  185.019042
SE                1727.6925    8396.67                   42.0  207.479167
SP               67625.4100  472238.07                   73.0  149.219834
TO                1834.5400    5144.32                   39.0  241.255143

                                                                           \
                       std        min         25%         50%         75%
customer_state
AC              215.027754  33.450000   87.400000  172.735000  231.475833
AL              329.273173  15.490000   97.005000  149.520417  240.469323
AM              246.584835  14.737500   71.550000  115.024167  184.195000
AP              302.632474  59.800000  116.470000  135.448333  223.166667
BA              178.267592  12.900000   91.692311  121.955735  166.619826
CE              196.931770  29.990000   97.286667  149.900000  222.760377
DF              246.414239  24.326667   82.140000  122.508750  173.393333
ES              373.453073  12.900000   88.401270  117.092766  166.749333
GO              258.024440  16.125000   97.607917  130.826871  176.647927
MA              228.530841  27.900000   93.330159  150.303750  205.940085
MG              176.083462  12.900000   81.916282  123.941242  168.673418
MS              186.194145   6.800000   76.831333  136.500000  193.972632
MT              436.458265  19.490000  116.281498  167.425227  248.082472
PA              204.324628  27.000000  104.533382  141.348486  212.974643
PB              339.162428  35.900000  122.635837  170.190000  280.475000
PE              203.551642  17.400000   97.210652  129.990000  195.144110
PI              135.545341  25.000000  103.172308  153.500000  207.752500
PR              237.825278   9.042857   66.688750  119.819477  150.816154
RJ              166.981095  25.800000   92.330673  127.498750  163.324126
RN              123.694191  16.900000   86.426174  152.813000  235.426695
RO              340.645542  19.900000   88.588929  126.617647  203.723000
RR              215.110862  13.650000  102.142000  172.700000  244.000000
RS              187.710605  24.990000   96.288929  131.333663  162.695120
SC              210.029675  19.900000   86.312000  130.392925  192.559459
SE              218.188117  18.450000   89.820160  134.995000  220.473750
SP              152.434467  41.525455   78.316667  116.618430  161.833119
TO              358.533022  24.713333   88.231970  150.410833  207.019062


                        max
customer_state
AC              1200.000000
AL              1476.300000
AM              1340.000000
AP              1437.000000
BA              1107.578421
CE              1182.798333
DF              1797.831667
ES              2686.000000
GO              1779.985000
MA              1357.396000
MG              1165.166667
MS              1092.945000
MT              2919.400000
PA               979.000000
PB              1782.000000
PE              1122.384000
PI               783.330000
PR              1669.245000
RJ              1096.572500
RN               719.950000
RO              1999.000000
RR               949.900000
RS              1068.361250
SC              1213.996000
SE              1200.000000
SP              1239.865400
TO              1999.000000

[27 rows x 32 columns]

In [13]:
from IPython.display import display

for column in ["category_order_count", "order_item_line_count", "category_gmv", "category_gmv_per_order"]:
    max_index = df_category[column].idxmax()
    print(f"\n{column}")
    display(df_category.loc[max_index, ["customer_state", "product_category", column]])

category_order_count

customer_state                      SP
product_category        bed_bath_table
category_order_count              4347
Name: 1276, dtype: object

order_item_line_count

customer_state                       SP
product_category         bed_bath_table
order_item_line_count              5157
Name: 1276, dtype: object

category_gmv

customer_state                  SP
product_category    bed_bath_table
category_gmv             472238.07
Name: 1276, dtype: object

category_gmv_per_order

customer_state                                MT
product_category          signaling_and_security
category_gmv_per_order                    2919.4
Name: 620, dtype: object

In [18]:
weighted_average_category_order_value = (
    df_category["category_gmv"].sum() / df_category["category_order_count"].sum()
)

weighted_ave_order_item_line_count = (
    df_category["category_gmv"].sum() / df_category["order_item_line_count"].sum()
)

print(weighted_average_category_order_value)
print(weighted_ave_order_item_line_count)

135.91737026604713
119.98056308247955

In [46]:
df_product_category = (
    df_category
    .groupby("product_category", as_index=False)
    .agg(
        category_order_count=("category_order_count", "sum"),
        order_item_line_count=("order_item_line_count", "sum"),
        category_gmv=("category_gmv", "sum"),
        category_gmv_per_order=("category_gmv_per_order", "sum")
    )
)

df_product_category["average_order_value"] = (
    df_product_category["category_gmv"] / df_product_category["category_order_count"]
)

df_product_category["average_order_line_value"] = (
    df_product_category["category_gmv"] / df_product_category["order_item_line_count"]
)

df_product_category = df_product_category.sort_values(
    "category_gmv",
    ascending=False
).reset_index(drop=True)

display(df_product_category)

,product_category,category_order_count,order_item_line_count,category_gmv,category_gmv_per_order,average_order_value,average_order_line_value
0,health_beauty,8647,9465,1233131.72,4779.359464,142.608040,130.283330
1,watches_gifts,5495,5859,1166176.98,6250.292787,212.225110,199.040276
2,bed_bath_table,9272,10953,1023434.76,3480.452467,110.379072,93.438762
3,sports_leisure,7530,8431,954852.55,3992.154589,126.806448,113.254958
4,computers_accessories,6530,7644,888724.61,4339.976643,136.098715,116.264339
...,...,...,...,...,...,...,...
69,flowers,29,33,1110.04,334.588786,38.277241,33.637576
70,home_comfort_2,24,30,760.27,245.040455,31.677917,25.342333
71,cds_dvds_musicals,12,14,730.00,243.333333,60.833333,52.142857
72,fashion_childrens_clothes,7,7,519.95,309.972500,74.278571,74.278571
73,security_and_services,2,2,283.29,283.290000,141.645000,141.645000

In [29]:
df_state = (
    df_category
    .groupby("customer_state", as_index=False)
    .agg(
        category_order_count=("category_order_count", "sum"),
        order_item_line_count=("order_item_line_count", "sum"),
        category_gmv=("category_gmv", "sum"),
        category_gmv_per_order=("category_gmv_per_order", "sum")
    )
)

df_state["average_order_value"] = (
    df_state["category_gmv"] / df_state["category_order_count"]
)

df_state["average_order_line_value"] = (
    df_state["category_gmv"] / df_state["order_item_line_count"]
)

df_state = df_state.sort_values(
    "category_gmv",
    ascending=False
).reset_index(drop=True)

display(df_state)

,customer_state,category_order_count,order_item_line_count,category_gmv,category_gmv_per_order,average_order_value,average_order_line_value
0,SP,40829,46448,5067633.16,10893.047905,124.118474,109.103366
1,RJ,12470,14143,1759651.13,11701.571113,141.110756,124.418520
2,MG,11457,12916,1552481.83,11926.883595,135.505091,120.198345
3,RS,5407,6134,728897.47,11616.945741,134.806264,118.829063
4,PR,4963,5649,666063.51,10855.128039,134.205825,117.908216
5,SC,3573,4097,507012.13,12026.237714,141.900960,123.752045
6,BA,3281,3683,493584.14,11184.105696,150.437105,134.016872
7,DF,2092,2355,296498.41,11158.429271,141.729641,125.901660
8,GO,1980,2277,282836.70,11706.161815,142.846818,124.214625
9,ES,2007,2225,268643.45,11489.073120,133.853239,120.738629
10,PE,1599,1746,251889.49,11051.574689,157.529387,144.266604
11,CE,1287,1426,219757.38,10625.699206,170.751655,154.107560
12,PA,951,1054,174470.59,11112.566263,183.460137,165.531869
13,MT,894,1037,152191.62,14910.196299,170.236711,146.761446
14,MA,721,800,117009.38,9518.765778,162.287628,146.261725
15,MS,704,811,115429.97,9779.700005,163.963026,142.330419
16,PB,518,586,112586.82,13476.921588,217.349073,192.127679
17,PI,479,523,84721.00,8715.029470,176.870564,161.990440
18,RN,477,521,82105.66,7902.767326,172.129266,157.592438
19,AL,397,427,78855.72,11651.037698,198.629018,184.673817
20,SE,336,375,56574.19,8714.124993,168.375565,150.864507
21,TO,275,310,48402.51,9408.950579,176.009127,156.137129
22,RO,245,273,45682.76,8989.309321,186.460245,167.336117
23,AM,145,163,22155.84,7422.916071,152.798897,135.925399
24,AC,81,91,15930.97,5630.788468,196.678642,175.065604
25,AP,67,81,13374.81,5017.629310,199.624030,165.121111
26,RR,41,46,7057.47,3526.729500,172.133415,153.423261

In [30]:
total_category_orders = df_state["category_order_count"].sum()
total_category_orders_line = df_state["order_item_line_count"].sum()
total_category_gmv = df_state["category_gmv"].sum()

df_state["order_share_pct"] = (
    df_state["category_order_count"] / total_category_orders * 100
)
df_state["order_line_pct"] = (
    df_state["order_item_line_count"] / total_category_orders_line * 100
)
df_state["gmv_share_pct"] = (
    df_state["category_gmv"] / total_category_gmv * 100
)

# GMVの大きい上位10州を表示する
display(
    df_state[
        [
            "customer_state",
            "category_order_count",
            "order_item_line_count",
            "order_share_pct",
            "order_line_pct",
            "category_gmv",
            "gmv_share_pct",
            "average_order_value",
            "average_order_line_value"
        ]
    ].head(10).round(2)
)

,customer_state,category_order_count,order_item_line_count,order_share_pct,order_line_pct,category_gmv,gmv_share_pct,average_order_value,average_order_line_value
0,SP,40829,46448,41.97,42.15,5067633.16,38.33,124.12,109.10
1,RJ,12470,14143,12.82,12.83,1759651.13,13.31,141.11,124.42
2,MG,11457,12916,11.78,11.72,1552481.83,11.74,135.51,120.20
3,RS,5407,6134,5.56,5.57,728897.47,5.51,134.81,118.83
4,PR,4963,5649,5.10,5.13,666063.51,5.04,134.21,117.91
5,SC,3573,4097,3.67,3.72,507012.13,3.83,141.90,123.75
6,BA,3281,3683,3.37,3.34,493584.14,3.73,150.44,134.02
7,DF,2092,2355,2.15,2.14,296498.41,2.24,141.73,125.90
8,GO,1980,2277,2.04,2.07,282836.70,2.14,142.85,124.21
9,ES,2007,2225,2.06,2.02,268643.45,2.03,133.85,120.74

州ごとの集計では、sales_baseline_by_month_stateとほぼ同じ結果になった。
続いて、上位３州でなんのカテゴリーがgmvに貢献しているのかを調べる。

In [45]:
df_major_category = (
    df_category
    .groupby(["customer_state", "product_category"], as_index=False)
    .agg(
        category_order_count=("category_order_count", "sum"),
        order_item_line_count=("order_item_line_count", "sum"),
        category_gmv=("category_gmv", "sum"),
        category_gmv_per_order=("category_gmv_per_order", "sum")
    )
)

df_major_category["average_order_value"] = (
    df_major_category["category_gmv"] / df_major_category["category_order_count"]
)

df_major_category["average_order_line_value"] = (
    df_major_category["category_gmv"] / df_major_category["order_item_line_count"]
)

target_states = ["SP", "RJ", "MG"]

df_selected = df_major_category[
    df_major_category["customer_state"].isin(target_states)
    ]

df_selected["customer_state"] = (
    df_selected["customer_state"]
    .astype(pd.CategoricalDtype(categories=target_states,ordered=True))
)

df_selected = df_selected.sort_values(
    ["customer_state", "category_gmv"],
    ascending=[True, False]
    )

display(df_selected)

,customer_state,product_category,category_order_count,order_item_line_count,category_gmv,category_gmv_per_order,average_order_value,average_order_line_value
1283,SP,bed_bath_table,4347,5157,472238.07,108.635397,108.635397,91.572245
1319,SP,health_beauty,3715,4125,453916.48,122.184786,122.184786,110.040359
1348,SP,watches_gifts,2090,2234,421546.60,201.696938,201.696938,188.695882
1342,SP,sports_leisure,3216,3576,375044.87,116.618430,116.618430,104.878319
1291,SP,computers_accessories,2616,3099,341044.96,130.368869,130.368869,110.050003
...,...,...,...,...,...,...,...,...
506,MG,fashion_sport,2,2,264.90,132.450000,132.450000,132.450000
533,MG,pc_gamer,1,1,129.99,129.990000,129.990000,129.990000
509,MG,flowers,4,5,96.29,24.072500,24.072500,19.258000
498,MG,diapers_and_hygiene,1,1,43.00,43.000000,43.000000,43.000000
520,MG,home_comfort_2,3,3,38.70,12.900000,12.900000,12.900000